# Esta propiedad le dice a Gradle que permita el uso de las librerías modernas de AndroidX.
android.useAndroidX=true
# Esta propiedad migra automáticamente las librerías antiguas para que sean compatibles con AndroidX.
android.enableJetifier=true
# Esta propiedad soluciona el error "Cannot mutate dependencies" permitiendo la modificación de configuraciones.
android.dependency.verification=off